const repository = "https://github.com/BVBGurke/PW-Tool";

function Mark() { return <span className="mark" aria-hidden="true" />; }

export default function App() {
  return <div className="manual">
    <aside className="rail"><Mark /><span>PW—SITE</span><i /><nav><a href="#policy">01</a><a href="#lan">02</a><a href="#start">03</a></nav><small>LOCAL / CONTROLLED</small></aside>
    <header><a className="brand" href="#top"><Mark />PW<span>/</span>TOOL</a><nav><a href="#policy">Prinzip</a><a href="#lan">LAN</a><a href="#start">Start</a></nav><a href={repository}>Repository ↗</a></header>
    <main id="top">
      <section className="hero shell"><div><div className="index">01 / LOCAL RANDOMNESS</div><p className="eyebrow">PYTHON BACKEND / REACT FRONTEND</p><h1>Erzeuge lokal.<br /><em>Kontrolliere</em><br />bewusst.</h1><p className="lead">PW-Tool verbindet eine klare OS-CSPRNG-Policy mit einer lokalen React-Anwendung. Kein Cloudkonto, kein unsichtbarer Zufallspfad.</p><div className="actions"><a className="button" href={repository}>Zum Repository ↗</a><a className="plain" href="#start">Installation →</a></div></div><div className="diagram"><div className="diagram-grid" /><Mark /><div className="shape" /><div className="meter">ENTROPY<strong>80</strong>CHARACTER FIELD</div></div></section>
      <section className="claims shell"><span><b>01</b> OS-CSPRNG</span><span><b>02</b> CPU / ARM64</span><span><b>03</b> Klare LAN-Grenzen</span></section>
      <section id="policy" className="policy shell"><div><div className="index">02 / CONSTRUCTION</div><p className="eyebrow">EIN NACHVOLLZIEHBARER PFAD</p><h2>Keine<br /><em>algorithmische</em><br />Lotterie.</h2></div><div className="cards"><article className="ink"><Mark /><h3>Direkte Policy</h3><p>Der sichtbare Generator nutzt OS-CSPRNG, garantierte Zeichenklassen, Rejection Sampling und einen CSPRNG-Shuffle.</p></article><article><Mark /><h3>Lokale Konten</h3><p>Für den LAN-Betrieb schützen Konten, serverseitige Sitzungen und eine lokale Datenbank die Anwendung.</p></article><article className="copper"><Mark /><h3>Grenzen sichtbar</h3><p>GPU bleibt Statusinformation. Die Hash-Demo ist eine lokale Selbstprüfung, kein Crack-Tool.</p></article></div></section>
      <section id="lan" className="lan shell"><div className="lan-title"><div className="index">03 / LAN RUNTIME</div><h2>Standard: lokal.<br />LAN: bewusst.</h2></div><div className="lan-table"><div><b>127.0.0.1</b><span>Standardbindung ohne Netzfreigabe</span><em>STANDARD</em></div><div><b>Vertrauenswürdiges LAN</b><span>Explizite Origins, Konten und Datenbank</span><em>OPT-IN</em></div><div><b>Öffentliches Internet</b><span>Nicht Teil des Produkts</span><em>AUSGESCHLOSSEN</em></div></div></section>
      <section className="hash shell"><div><div className="index">04 / HASH DEMO</div><h2>Prüfen,<br /><em>nicht</em> raten.</h2><p>Die scrypt-Demo nutzt einen selbst erzeugten Wert und zeigt nur Metadaten. Sie nimmt keine Fremdhashes oder Kandidatenlisten an.</p></div><ol><li><b>1</b>Frischer lokaler Demo-Wert</li><li><b>2</b>Neuer Salt, nicht angezeigt</li><li><b>3</b>scrypt auf dem CPU-Pfad</li><li><b>4</b>Einmalige Selbstprüfung</li></ol></section>
      <section id="start" className="start shell"><div><div className="index">05 / GET STARTED</div><h2>Dein Server.<br />Deine Kontrolle.</h2></div><div className="terminal"><span>TERMINAL / SHELL</span><code><b>$</b> git clone {repository}.git && cd PW-Tool<br /><b>$</b> ./setup.sh && ./start.sh</code><p>Die Setup-Skripte installieren bewusst Abhängigkeiten. Start-Skripte verändern die Umgebung nicht und beginnen standardmäßig nur auf localhost.</p></div></section>
    </main>
    <footer className="shell"><a className="brand" href="#top"><Mark />PW<span>/</span>TOOL</a><span>Lokale Passworterzeugung mit sichtbaren Grenzen.</span><a href={repository}>GitHub ↗</a></footer>
  </div>;
}
